#!/usr/bin/env bash
#Write a Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.
FILE="/etc/passwd"

while IFS=":" read -r USERNAME GROUP_ID HOME_DIRECTORY CMDSHELL USERID PASSWORD USERIDINFO
do
    echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $CMDSHELL. $USERID's place is protected by the passcode $PASSWORD, more info about the user here: $USERIDINFO"
done < "$FILE"
