#!/usr/bin/env bash
#Write a Bash script that loops from 1 to 10 and: some conditions.
i=0
while [ $i -lt 10 ]; do
	((i++))
	if [ $i == "4" ]; then
		echo "bad luck"
		elif [ $i == "8" ]; then
			echo "good luck"
		else
			echo "Best School"	
	fi
done
