#!/usr/bin/env bash
#Write a Bash script that loops from 1 to 10 and: some conditions.
i=0
while [ $i -lt 9 ]; do
	echo "Best School"
	((i++))
	if [ $i == "3" ]; then
		echo "Bad luck"
		elif [ $i == "7" ]; then
			echo "Good luck"
		else
			echo "Best School"	
	fi
done
