#!/usr/bin/env bash
#bash script that displays numbers from 1 to 20 and luck messages
i=1
while [ $i -lt 21 ]; do
	echo $i
	case "$i" in
		"3") 
		echo "bad luck from China"
		;;
		"9")
		echo "bad luck from Japan"
		;;
		"16")
		echo "bad luck from Italy"
		;;
	esac
	((i++))
done
		
